extends RefCounted
class_name GameEnums

enum Race { HUMAN, ELF, OGRE, FAIRY, UNDEAD, BEAST }
enum ClassType { ATTACKER, TANK, SNIPER, SUPPORT, STEALTH }
enum CardType { CREATURE, MASTER, SUPPORT }
enum SkillEffectType {
	ALLY_HEAL,
	SUMMON_SKELETONS,
	AOE_PHYSICAL_DEFENSE_BREAK,
	HYBRID_STRIKE_MANA_SUPPRESS,
	PHYSICAL_LIFESTEAL_STRIKE,
	MAGIC_AOE_SLOW,
	SELF_EXPLOSION,
	EXECUTE_MAGIC_STRIKE,
	PHYSICAL_SHIELD_REFLECT,
	MANA_SUPPRESS_AURA,
	SELF_SACRIFICE_MANA_GIFT,
	TARGET_MAGIC_DEFENSE_BREAK,
	ALLY_MAGIC_CRIT_GIFT,
	TARGET_HEAVY_SLOW,
	TARGET_PHYSICAL_VULNERABILITY,
	POUNCE_MAGIC_HUNTER_STUN,
	SELF_BASIC_ATTACK_BLOCK,
	AOE_PHYSICAL_ATTACK_SLOW,
	MISSING_HEALTH_PHYSICAL_STRIKE,
	SELF_BERSERK_FRENZY,
	SELF_CLEAVE_BUFF,
	TARGET_PHYSICAL_DEFENSE_BREAK_ZERO,
	GAIN_NEXT_ROUND_GOLD,
	ALLY_HEAL_PERCENT,
	ADJACENT_LIFESTEAL_GIFT,
	ADJACENT_MANA_GIFT,
	MASTER_TAUNT_AURA,
}
enum SupportCardEffectType {
	PLAYER_LIFE_HEAL,
	UNIT_ATTACK_BUFF,
	MAGIC_ATTACK_MULTIPLIER,
	START_STEALTH,
	DELAYED_BLIND_FIELD,
	DEATH_MANA_PACT,
	CELL_TRAP_STUN,
	CONDITIONAL_NEXT_ROUND_GOLD,
	CONDITIONAL_TRIBUTE_STEAL,
	PHYSICAL_DEFENSE_RATIO_BUFF,
	PHYSICAL_ATTACK_RANGE_BUFF,
	OPENING_REPOSITION,
}
enum TeamSide { PLAYER, ENEMY }
enum BattleState { SETUP, PREP, BATTLE, ROUND_END, MATCH_END }
enum MatchPhase { LOBBY, ROUND_PAIRING, ROUND_PREP, ROUND_BATTLE, ROUND_RESULT, MATCH_END }
enum BoardViewMode { SELF_ONLY, FULL_BATTLE }
